import { Inter } from 'next/font/google'
import Script from 'next/script';
import "../src/index.css"
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script src="https://kit.fontawesome.com/81a5c3f631.js" crossorigin="anonymous"></Script>
    </html>
  )
}
